create or replace table print_snapshot_std (
    read_time            timestamp_ntz,
    topic                string,
    workcenter           string,
    equipment            string,
    status               integer,
    dmc_code             string,
    rfid_code            string,
    print_cnt            number,
    print_spd            integer,
    print_stroke         integer,
    ink_ret_spd          integer,
    ink_ret_stroke       integer,
    off_contact_hgt      integer,
    off_contact_ratio    float,
    silk_screen_life     number,
    silk_screen_status   string,
    ir1_maxtemp          float,
    ir1_mintemp          float,
    ir1_curtemp          float,
    ir2_maxtemp          float,
    ir2_mintemp          float,
    ir2_curtemp          float,
    dry1_speed           float
);
